# Generated by Django 5.1.1 on 2024-09-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_session_name_alter_session_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="set",
            name="reps",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="set",
            name="rir",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="set",
            name="weight",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
