# Generated by Django 5.1.1 on 2024-10-11 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_set_reps_alter_set_rir_alter_set_weight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="performancemetric",
            name="date_predicted",
        ),
        migrations.AddField(
            model_name="performancemetric",
            name="session",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="api.session"
            ),
            preserve_default=False,
        ),
    ]
